# Generated by Django 5.2.7 on 2025-11-02 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('human', 'Human'), ('animal', 'Animal'), ('environmental', 'Environmental')], max_length=20)),
                ('symptoms', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('health_worker', 'Health Worker'), ('veterinary_officer', 'Veterinary Officer'), ('environment_officer', 'Environment Officer')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('number_of_cases', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.disease')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.district')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test1.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_reports/')),
                ('transcribed_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('added_to_dashboard', 'Added to Dashboard')], default='pending', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.userprofile')),
            ],
        ),
    ]
